# Generated by Django 3.2 on 2021-04-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20210407_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address_2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
